<a href="https://colab.research.google.com/github/Sahana-K-2002/CODSOFT/blob/main/bankchurn_codsoft.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
import pandas as pd

In [37]:
data=pd.read_csv('churn.csv')

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [39]:
num=data['Geography'].value_counts()

In [40]:
print(num)

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64


In [41]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

data['Gender']=le.fit_transform(data['Gender'])
data['Geography']=le.fit_transform(data['Geography'])

In [42]:
x=data.drop(['Exited','Surname','CustomerId','HasCrCard','RowNumber','Tenure','EstimatedSalary'],axis=1)
y=data['Exited']

In [43]:
corr=data.corr()['Exited']
print(corr)

RowNumber         -0.016571
CustomerId        -0.006248
CreditScore       -0.027094
Geography          0.035943
Gender            -0.106512
Age                0.285323
Tenure            -0.014001
Balance            0.118533
NumOfProducts     -0.047820
HasCrCard         -0.007138
IsActiveMember    -0.156128
EstimatedSalary    0.012097
Exited             1.000000
Name: Exited, dtype: float64


<ipython-input-43-5325d7742ae6>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr=data.corr()['Exited']


In [44]:
cls=data['Exited'].value_counts()
print(cls)

0    7963
1    2037
Name: Exited, dtype: int64


In [45]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [46]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train_n=sc.fit_transform(x_train)
x_test_n=sc.transform(x_test)

In [47]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train_n,y_train)
y_pred=classifier.predict(x_test_n)
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test,y_pred)
print(acc)

[[1542   53]
 [ 330   75]]
0.8085


In [48]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train_n, y_train)

KNeighborsClassifier()

In [49]:
y_pred=classifier.predict(x_test_n)
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test,y_pred)
print(acc)

[[1479  116]
 [ 201  204]]
0.8415


In [50]:
from sklearn.tree import DecisionTreeClassifier
dtclassifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dtclassifier.fit(x_train_n, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [51]:
y_pred=dtclassifier.predict(x_test_n)
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test,y_pred)
print(acc)

[[1364  231]
 [ 196  209]]
0.7865


In [52]:
from sklearn.ensemble import RandomForestClassifier
rfclassifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rfclassifier.fit(x_train_n, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [53]:
y_pred=rfclassifier.predict(x_test_n)
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test,y_pred)
print(acc)

[[1492  103]
 [ 202  203]]
0.8475


In [54]:
from xgboost import XGBClassifier
xgclassifier = XGBClassifier()
xgclassifier.fit(x_train_n, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [55]:
y_pred=xgclassifier.predict(x_test_n)
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test,y_pred)
print(acc)

[[1487  108]
 [ 198  207]]
0.847


In [56]:
from sklearn.ensemble import ExtraTreesClassifier
etc = ExtraTreesClassifier(n_estimators=200)
etc.fit(x_train_n, y_train)
y_pred=etc.predict(x_test_n)
accuracy_score(y_test,y_pred)

0.843

In [57]:
from sklearn.ensemble import VotingClassifier
ensemble = VotingClassifier(
    estimators=[('decision_tree', dtclassifier),
                ('knn',classifier),
                ('random_forest', rfclassifier),
                ('xgboost',xgclassifier)],
    voting='hard'  # You can use 'soft' for soft voting
)
ensemble.fit(x_train_n,y_train)
ensemble_predictions = ensemble.predict(x_test_n)
ensemble_accuracy = accuracy_score(y_test, ensemble_predictions)
cm=confusion_matrix(y_test,ensemble_predictions)
print(cm)
print(ensemble_accuracy)

[[1524   71]
 [ 223  182]]
0.853


In [58]:
from sklearn.ensemble import GradientBoostingClassifier
gb_classifier = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
gb_classifier.fit(x_train_n, y_train)
y_pred = gb_classifier.predict(x_test_n)
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test,y_pred)
print(acc)

[[1528   67]
 [ 198  207]]
0.8675


##after sampling

In [59]:
from imblearn.over_sampling import SMOTE
smote=SMOTE()

In [60]:
x_smote,y_smote=smote.fit_resample(x,y)

In [61]:
clscnt=y_smote.value_counts()
print(clscnt)

1    7963
0    7963
Name: Exited, dtype: int64


In [62]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_smote, y_smote, test_size = 0.2, random_state = 0)

In [63]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train_n=sc.fit_transform(x_train)
x_test_n=sc.transform(x_test)

## Logistic regression

In [64]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train_n,y_train)
y_pred=classifier.predict(x_test_n)
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test,y_pred)
print(acc)


[[1221  369]
 [ 336 1260]]
0.7787193973634652


## KNN

In [65]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train_n, y_train)

KNeighborsClassifier()

In [66]:
y_pred=classifier.predict(x_test_n)
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test,y_pred)
print(acc)

[[1281  309]
 [ 264 1332]]
0.82015065913371


## Decision tree

In [67]:
from sklearn.tree import DecisionTreeClassifier
dtclassifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dtclassifier.fit(x_train_n, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [68]:
y_pred=rfclassifier.predict(x_test_n)
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test,y_pred)
print(acc)

[[1539   51]
 [ 913  683]]
0.6974262397991211


## RandomForest Classification

In [69]:
from sklearn.ensemble import RandomForestClassifier
rfclassifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rfclassifier.fit(x_train_n, y_train)
y_pred=rfclassifier.predict(x_test_n)
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test,y_pred)
print(acc)

[[1342  248]
 [ 275 1321]]
0.8358443188951663


## XGboost

In [70]:
from xgboost import XGBClassifier
xgclassifier = XGBClassifier()
xgclassifier.fit(x_train_n, y_train)
y_pred=xgclassifier.predict(x_test_n)
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test,y_pred)
print(acc)

[[1348  242]
 [ 246 1350]]
0.8468298807281858


## Extratree classifier

In [71]:
from sklearn.ensemble import ExtraTreesClassifier
etc = ExtraTreesClassifier(n_estimators=200)
etc.fit(x_train_n, y_train)
y_pred=etc.predict(x_test_n)
accuracy_score(y_test,y_pred)

0.8471437539234149

## Gradient Boosting

In [72]:
from sklearn.ensemble import GradientBoostingClassifier
gb_classifier = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
gb_classifier.fit(x_train_n, y_train)
y_pred = gb_classifier.predict(x_test_n)
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test,y_pred)
print(acc)

[[1320  270]
 [ 279 1317]]
0.827683615819209
